nelmio_api_doc:
    documentation:
        info:
            title: Fridget data API
            description: This is is the api used for all fridget platforms
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/testview$|/doc$|/docs$) # Accepts routes under /api except /api/doc
